
name: SGSI_Build

on:
  workflow_dispatch:
    inputs:
      ROM_URL:
        description: 'ROM_URL'
        required: true
        default: 'https://get.pixelexperience.org/ZitpZUZNUWVmM2cwLzkzQzFaMW9FOUQyaFo1WnR0RWNhbXNzUTJEaUJvaDdnZkp2NlQ2ZlVOVlBrVzNub21lenpmMjJXZzFDdFc0Y0N4YkFJYUQ4bWp'
      ZIP_NAME:
        description: 'ZIP_NAME'
        required: true
        default: 'update.zip'
      OS_TYPE:
        description: 'OS_TYPE'
        required: true
        default: 'Generic'
      SGSI_TYPE:
        description: 'SGSI_TYPE(AB, A, or BOTH)'
        required: true
        default: 'AB'
      REPACK_NAME:
        description: 'REPACK_NAME'
        required: true
        default: 'SGSI.zip'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cleanup workspace
        run: |
          docker rmi `docker images -q`
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox* google* dotnet* powershell openjdk* php*
          sudo -E apt-get update
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
          df -h

      - name: Initializing Environment
        run: |
          sudo apt-get install -y git wget git zip unzip curl axel

      - name: Cloning SGSI source code
        run: |
          git clone --recurse-submodules https://github.com/xiaoxindada/SGSI-build-tool.git -b 12 $GITHUB_WORKSPACE/SGSI-build-tool

      - name: Setup sGSI tools requirements
        run: |
          sudo sed -i 's/USE_MIRROR_FOR_PIP\=true/USE_MIRROR_FOR_PIP\=false/' $GITHUB_WORKSPACE/SGSI-build-tool/setup.sh
          sudo bash $GITHUB_WORKSPACE/SGSI-build-tool/setup.sh
        # sudo apt purge openJDK*
        # java -version

      - name: Build SGSI
        run: |
          cd  $GITHUB_WORKSPACE/SGSI-build-tool
          sudo bash ./url2SGSI.sh "${{ steps.config.outputs.rom_url }}" "${{ steps.config.outputs.os_type }}" "${{ steps.config.outputs.build_type }}"

      - name: Repack Output File
        run: |
          cd $GITHUB_WORKSPACE/SGSI-build-tool
          mkdir -p upload
          zip -r ${{ steps.config.outputs.repack_name }} ./SGSI/*
          if [[ $(du -sb "${{ steps.config.outputs.repack_name }}" | awk '{print $1}') -gt 2097152000 ]];then
              echo -e "split packaging..."
              tar -cpzf - "${{ steps.config.outputs.repack_name }}" | split -d -b 1024m - "upload/${{ steps.config.outputs.repack_name }}"
          else
              mv "${{ steps.config.outputs.repack_name }}" "upload/${{ steps.config.outputs.repack_name }}"
          fi
          ls "upload"

      - name: Upload SGSI to GH-Release
        uses: ncipollo/release-action@v1.8.6
        with:
          artifacts: ${{ github.workspace }}/SGSI-build-tool/upload/*
          name: "${{ steps.config.outputs.os_type }}${{ steps.config.outputs.build_type }}-Android${{ steps.config.outputs.version }}-unpack"
          tag: "${{ steps.config.outputs.os_type }}${{ steps.config.outputs.build_type }}-${{ steps.config.outputs.version }}-${{ github.run_number }}"
          bodyFile: "${{ github.workspace}}/SGSI-build-tool/SGSI/build_info.txt"
          token: ${{ secrets.GITHUB_TOKEN }}
